name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  ARCHIVE_URL: https://downloads.mitmproxy.org/12.2.2/mitmproxy-12.2.2-windows-x86_64.zip

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: build
        shell: bash
        run: |
          set -euo pipefail

          TAG_NAME="${GITHUB_REF_NAME}"
          VERSION="${TAG_NAME#v}"
          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          ASSET_NAME="${REPO_NAME}_${VERSION}_windows_amd64.zip"
          ASSET_NAME_EN="${REPO_NAME}_${VERSION}_windows_amd64_en.zip"

          echo "ASSET_NAME=${ASSET_NAME}" >> "${GITHUB_ENV}"
          echo "ASSET_NAME_EN=${ASSET_NAME_EN}" >> "${GITHUB_ENV}"

          curl -fL "${ARCHIVE_URL}" -o mitmproxy.zip
          unzip mitmproxy.zip

          mkdir -p "${REPO_NAME}/bin"
          mv src "${REPO_NAME}"
          mv mitmdump.exe "${REPO_NAME}/bin"

          cp spotify-helper.vbs spotify-helper-auth.vbs "${REPO_NAME}"
          mv "${REPO_NAME}/src/spotify-helper-en.py" .
          zip -r "${ASSET_NAME}" "${REPO_NAME}"

          cp spotify-helper-en.vbs "${REPO_NAME}"
          rm "${REPO_NAME}/spotify-helper.vbs"
          rm "${REPO_NAME}/spotify-helper-auth.vbs"
          cp spotify-helper-en.py "${REPO_NAME}/src"
          rm "${REPO_NAME}/src/spotify-helper.py"
          rm "${REPO_NAME}/src/ws_tunnel.py"
          zip -r "${ASSET_NAME_EN}" "${REPO_NAME}"


      - name: release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            ${{ env.ASSET_NAME }}
            ${{ env.ASSET_NAME_EN }}
