name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  ARCHIVE_URL: https://downloads.mitmproxy.org/12.2.2/mitmproxy-12.2.2-windows-x86_64.zip

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: build
        shell: bash
        run: |
          set -euo pipefail

          TAG_NAME="${GITHUB_REF_NAME}"
          VERSION="${TAG_NAME#v}"
          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          ASSET_NAME="${REPO_NAME}_${VERSION}_windows_amd64.zip"

          echo "ASSET_NAME=${ASSET_NAME}" >> "${GITHUB_ENV}"

          curl -fL "${ARCHIVE_URL}" -o mitmproxy.zip
          unzip mitmproxy.zip

          mkdir -p "${REPO_NAME}/bin"
          mv mitmdump.exe "${REPO_NAME}/bin"
          cp spotify-helper.vbs _spotify.ps1 "${REPO_NAME}"
          mv src "${REPO_NAME}"
          zip -r "${ASSET_NAME}" "${REPO_NAME}"

      - name: release
        uses: softprops/action-gh-release@v3
        with:
          files: ${{ env.ASSET_NAME }}
